# Generated by Django 4.2.3 on 2023-07-28 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0002_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='student_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendances.student'),
        ),
    ]
