# Generated by Django 4.2.3 on 2023-07-28 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0003_customuser_student_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
