# Generated by Django 4.2.3 on 2023-07-31 12:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0004_availabledate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='practiceavailable',
            old_name='created_at',
            new_name='created_date',
        ),
        migrations.RemoveField(
            model_name='practiceavailable',
            name='name',
        ),
        migrations.AddField(
            model_name='availabledate',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='availabledate',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='availabledate',
            name='name',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='practiceavailable',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
