# Generated by Django 4.2.3 on 2023-07-31 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0005_alter_notice_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='practiceavailable',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
