# Generated by Django 4.2.3 on 2023-07-31 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0008_practiceavailable_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practiceavailable',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='practiceavailable',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
