# Generated by Django 4.2.3 on 2023-08-01 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0012_availabledate_alter_attendance_available_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicedatedetail',
            name='is_attending',
            field=models.BooleanField(default=None),
        ),
    ]
