# Generated by Django 4.2.3 on 2023-08-01 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0013_alter_practicedatedetail_is_attending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicedatedetail',
            name='practice_date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendances.availabledate'),
        ),
    ]
