# Generated by Django 4.2.3 on 2023-08-01 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0015_alter_practicedatedetail_is_attending'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PracticeDate',
        ),
    ]
