# Generated by Django 4.2.3 on 2023-08-02 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0018_remove_votechoice_vote_remove_votechoice_voters_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availabledate',
            name='attendees',
        ),
    ]
