# Generated by Django 4.2.3 on 2023-08-02 18:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0019_remove_availabledate_attendees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='available_date',
        ),
        migrations.AddField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
