# Generated by Django 4.2.3 on 2023-08-02 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0020_remove_attendance_available_date_attendance_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practiceavailable',
            name='title',
        ),
    ]
